import { formatKey, type KeyFormatContext, keyFormatUsesParents } from "$shared/keyFormat";
import type { NodeInfo, TolgeeConfig } from "$shared/types";

/**
 * Builds the `formatKey` context from a node's fields.
 *
 * Single source of truth for the placeholder inputs, so BOTH the in-row prefill
 * and the "Generate key names" bulk action feed `formatKey` identical values —
 * including the parent placeholders ({component}/{frame}/{artboard}/{section}/
 * {group}), which are resolved main-side and left undefined when the node has
 * no such ancestor (or the format doesn't use one).
 */
export function keyContextForNode(node: NodeInfo): KeyFormatContext {
  return {
    elementName: node.name,
    elementText: node.characters,
    component: node.component,
    instance: node.instance,
    frame: node.frame,
    artboard: node.artboard,
    section: node.section,
    group: node.group,
  };
}

/**
 * The format-generated key SUGGESTION for a node, given the current config.
 *
 * Drives the in-row prefill (NodeListItem persists this for empty unconnected
 * keys). The "Generate key names" bulk action shares the same underlying
 * `formatKey` primitive but with a user-editable template, so both stay
 * consistent through that one helper.
 *
 * Returns "" when prefill is off or no template is configured — callers treat
 * an empty result as "nothing to generate".
 */
export function prefillKeyFor(
  node: NodeInfo,
  config: Partial<TolgeeConfig> | null | undefined,
): string {
  if (!config?.prefillKeyFormat || !config.keyFormat) return "";
  return formatKey(config.keyFormat, keyContextForNode(node), config.variableCasing);
}

/**
 * Per-node prefill decisions for this plugin session: node id → the format
 * signature (key format + casing) the decision was made under.
 *
 * Module-level on purpose: the decision used to live in each `NodeListItem`
 * instance, but the virtualized list re-mounts rows on scroll, so a per-row
 * flag "forgot" that the user had explicitly cleared a key and re-applied the
 * prefill on every remount. Session scope makes an explicit clear stick for
 * as long as the plugin is open.
 *
 * The signature makes format changes work per node instead of as a global
 * one-shot: a node decided under format A is simply "undecided" once the
 * format is B, so it regenerates whenever it next shows up — even if the
 * first pass after the change ran on a stale snapshot (parent placeholder
 * names arrive only with the re-scan that follows a format save).
 */
const settled = new Map<string, string>();

/**
 * Compute the prefill batch for a selection. Decision per unconnected node:
 * - first seen this session (not in `settled`): fill only an EMPTY key —
 *   keys persisted earlier (manual or generated by a previous session) are
 *   never overwritten just by opening the plugin;
 * - decided under the CURRENT format: leave alone — a manual key or an
 *   explicit clear sticks;
 * - decided under an OLDER format: regenerate, overwriting the previous
 *   value — production parity for "I changed the key format" (its per-node
 *   suggestion query had the format in its cache key, so a format change
 *   rewrote every unconnected key; we also trigger on casing, which
 *   production missed).
 * A node whose suggestion comes out empty stays undecided and is retried on
 * the next pass (typically once the re-scan delivers its parent names).
 * Pure decision logic — the caller persists the result.
 */
/** Any parent placeholder name resolved on this snapshot? The scan fills
 *  these only when the SAVED format uses them, so right after a format save
 *  the current snapshot may predate that scan — generating from it would
 *  persist a partial key (`formatKey` drops empty placeholders). */
function hasParentContext(n: NodeInfo): boolean {
  return (
    n.component !== undefined ||
    n.instance !== undefined ||
    n.frame !== undefined ||
    n.artboard !== undefined ||
    n.section !== undefined ||
    n.group !== undefined
  );
}

export function pendingPrefills(
  nodes: NodeInfo[],
  config: Partial<TolgeeConfig> | null | undefined,
): { id: string; key: string; ns: string }[] {
  if (!config?.prefillKeyFormat || !config.keyFormat) return [];
  const signature = `${config.keyFormat} ${config.variableCasing ?? ""}`;
  const needsParents = keyFormatUsesParents(config.keyFormat);

  const out: { id: string; key: string; ns: string }[] = [];
  for (const n of nodes) {
    const decidedUnder = settled.get(n.id);
    if (decidedUnder === signature) continue;
    if (n.connected) {
      settled.set(n.id, signature);
      continue;
    }
    // Not seen this session + already has a key → keep it (boot must never
    // rewrite persisted keys). A key decided under an older format → fall
    // through and regenerate.
    if (decidedUnder === undefined && (n.key ?? "") !== "") {
      settled.set(n.id, signature);
      continue;
    }
    // Parent-based format, but this snapshot has no resolved ancestors —
    // stay undecided until the follow-up scan delivers them. (A text node
    // with genuinely no eligible ancestor never prefills under such a
    // format; acceptable for the page-root edge case.)
    if (needsParents && !hasParentContext(n)) continue;
    const key = prefillKeyFor(n, config);
    if (!key) continue; // no suggestion (yet) — stay undecided and retry
    settled.set(n.id, signature);
    if (key !== (n.key ?? "")) {
      out.push({ id: n.id, key, ns: n.ns ?? config.namespace ?? "" });
    }
  }
  return out;
}

/** Test hook — the session-scoped decision memory is module state. */
export function resetPrefillSettled(): void {
  settled.clear();
}
